Update collect-branch.yml Error catch on Code commit if no changes

diff --git a/.github/workflows/collect-branch.yml b/.github/workflows/collect-branch.yml
--- a/.github/workflows/collect-branch.yml
+++ b/.github/workflows/collect-branch.yml
@@ -130,7 +130,11 @@ jobs:
         run: |
           git submodule update --init --recursive --remote
           git commit -am "Update Submodules"
-          git push
+          if [ $? -eq 1 ];then
+            echo "No push required"
+          else
+            git push
+          fi
 
       - name: Bundle Repo1 code base for ${{ vars.COLLECTOR }}
         run: |
